config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'
  resources :users, except: :index
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: :create
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :moderator_id, presence: true
  validates :title, presence: true, uniqueness: true

  belongs_to :moderator, class_name: :User, foreign_key: :moderator_id
  has_many :post_subs
  has_many :posts, through: :post_subs, source: :post
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :update]
  before_action :require_login, only: [:new, :create]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def index
    @subs = Sub.all
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy!
    redirect_to root_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless @sub.moderator_id == current_user.id
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<h1><%= title %></h1>

<form action="<%= action %>" method="post">
  <%= render 'shared/csrf_token' %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Title:
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <br>

  <label>Description (optional):
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>
  <br>

  <input type='submit' value='<%= title %>'>
</form>

app/views/subs/_sub.html.erb
<h2><%= link_to sub.title, sub_url(sub) %></h2>
<p><%= sub.description %></p>

app/views/subs/edit.html.erb
<%= render 'form', sub: @sub, action: sub_url(@sub), title: 'Edit sub', method: "patch" %>

app/views/subs/index.html.erb
<h1>Subs</h2>
<%= render @subs %>
<%= link_to "Add Sub", new_sub_url %>

app/views/subs/new.html.erb
<%= render 'form', sub: @sub, action: subs_url, title: 'Add sub', method: "post" %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p><%= @sub.description %></p>
<%= render @posts %><br/>
<%= link_to "Add Post", new_sub_post_url(@sub) %><br/>
<% if current_user.id == @sub.moderator_id %>
  <%= link_to "Edit Sub", edit_sub_url(@sub) %><br/>
  <%= link_to "Delete Sub", sub_url(@sub), method: :delete %><br/>
<% end %>
<%= link_to "All Subs", root_url %>