config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'
  resources :users, except: :index
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: :create
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  validates :subs, length: { minimum: 1 }

  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments, as: :commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author, only: [:edit, :update]
  before_action :require_login, only: [:new, :create]

  def new
    @post = Post.new
    flash.now[:sub_ids] = [params[:sub_id]]
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      flash.now[:sub_ids] = params[:post][:sub_ids]
      @subs = Sub.all
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    flash.now[:sub_ids] = @post.subs.pluck(:id).map(&:to_s)
    @subs = Sub.all
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      flash.now[:sub_ids] = params[:post][:sub_ids]
      @subs = Sub.all
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless @post.author_id == current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h1><%= title %></h1>
<form action="<%= action %>" method="post">
  <%= render 'shared/csrf_token' %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label><br/>
  <label>URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label><br/>
  <label>Content:
    <textarea type="text" name="post[content]"><%= post.content %></textarea>
  </label><br/>
  <p>Subs:</p>
  <% subs.each do |sub| %>
    <label><input
      type="checkbox"
      name="post[sub_ids][]"
      value='<%= sub.id %>'
      <%= "checked" if flash[:sub_ids].try(:include?, sub.id.to_s) %>>
      <%= sub.title %>
    </label>
    <br>
  <% end %>
  <input type="submit" value="<%= title %>">
</form>

app/views/posts/_post.html.erb
<%= link_to post.title, post.url %>
<%= post.content %>

app/views/posts/edit.html.erb
<%= render 'form', title: 'Edit post',
                   action: post_url(@post),
                   method: 'patch',
                   subs: @subs,
                   post: @post %>

app/views/posts/new.html.erb
<%= render 'form', title: 'Add post',
                   action: sub_posts_url,
                   method: 'post',
                   subs: @subs,
                   post: @post %>

app/views/posts/show.html.erb
<h2><%= link_to @post.title, @post.url %></h2>
<p><%= @post.content %></p>

<% if @post.author_id == current_user.id %>
  <%= link_to "Edit Post", edit_post_url(@post) %>
  <%= link_to "Delete Post", post_url(@post), method: :delete %>
<% end %>

<%= render @comments %>
<%= link_to "Add Comment", new_post_comment_url(@post) %>